### add category
POST http://localhost:8080/admin/category/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMyMzUxNzAsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2OTMzMjE1NzAsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.YjU6EDD_oXQFH-o0dKZf29f7t4al5tuwfVVlbLwTulMqeWeZXkYpxAqePMM6Eqi1_fABFLUtPkaqRAW1bc3XwQ
Content-Type: application/json

{
  "name": {
    "uz": "Naushnik1",
    "ru": "Ru Naushnik1",
    "eng": "Eng Naushnik1"
  }
}

### get by id
GET http://localhost:8080/private/category/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE2NTQxNzYsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjkxNzQwNTc2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Wacu0S1TIkPiK36PGbvpQ5gqNHvCrmBU76G0eA3TUBEvgGCOR2-73jKh_10D4PGdqi2WbHYkuGKHYKd_L3KgJA


### get all
GET http://localhost:8080/private/category/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE0ODQzMDMsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjkxNTcwNzAzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.mr_I3s203MVC8aoIC28YpZM4AUNHcIeoQG7VV3cj08SG9y0-FLfxw2WpmuzmKRFOWRJoirtk79ouvnjE-Hvd2A

