### add

POST http://localhost:8080/private/product/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTExNTA4MTMsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjkxMjM3MjEzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.SScaLffV5G4HihFC8FlCOi4uAj98RGs3O0erlsvgyyveucLBvt7rGxosBVSH_9Iuvkc7Z3PTUKD0MNYdO-EvEA
Content-Type: application/json

{
  "name": {
    "uz": "Telefon",
    "ru": "Ru telefon",
    "eng": "Eng telefon"
  },
  "categoryId": 1,
  "cost": 900000,
  "description": {
    "uz": " bu telefon",
    "ru": " eta telefon",
    "eng": "this is telefon"
  }
}

### get by id
GET http://localhost:8080/private/product/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTExNTA4MTMsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjkxMjM3MjEzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.SScaLffV5G4HihFC8FlCOi4uAj98RGs3O0erlsvgyyveucLBvt7rGxosBVSH_9Iuvkc7Z3PTUKD0MNYdO-EvEA

### get all
GET http://localhost:8080/private/product/all/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTExNTA4MTMsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjkxMjM3MjEzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.SScaLffV5G4HihFC8FlCOi4uAj98RGs3O0erlsvgyyveucLBvt7rGxosBVSH_9Iuvkc7Z3PTUKD0MNYdO-EvEA
